FROM prod.registry.devshift.net/osio-prod/base/openshift-nginx:latest
LABEL maintainer "Devtools <devtools@redhat.com>"
LABEL author "Devtools <devtools@redhat.com>"

ENV LANG=en_US.utf8
ENTRYPOINT /usr/bin/entrypoint.sh

USER root
ADD nginx.conf /etc/nginx/nginx.conf

COPY scripts/entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

RUN rm -f /usr/share/nginx/html/*

COPY dist /usr/share/nginx/html/launch
RUN chmod a+w /usr/share/nginx/html/launch

USER 997
